SegamApp/Areas/Admin/Controllers/UserProfileController.cs
using DataLayer;
using SegamApp.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SegamApp.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserProfileController : BaseController
    {
        SegamDBContext db = null;
        public UserProfileController()
        {
            db = new SegamDBContext();
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string pass1, string pass2)
        {
            if (ModelState.IsValid)
            {
                if (pass1 != pass2)
                {
                    ModelState.AddModelError("", "رمز عبور یکسان نیست");
                }
                else if(string.IsNullOrEmpty(pass1) || string.IsNullOrEmpty(pass2))
                {
                    ModelState.AddModelError("", "رمز عبور نمیتواند خالی باشد");
                }
                else
                {
                    int userId = CurrentUser.PersonID;
                    var person = db.Persons.Find(userId);
                    person.Password = pass1;
                    db.SaveChanges();

                    ViewBag.PassChangeSucc = "رمز عبور با موفقیت تغییر کرد";
                }
            }
            return View();
        }
    }
}

SegamApp/Areas/User/Controllers/UserProfileController.cs
using DataLayer;
using SegamApp.Controllers;
using System.Web.Mvc;

namespace SegamApp.Areas.User.Controllers
{
    [Authorize(Roles = "User")]
    public class UserProfileController : BaseController
    {
        SegamDBContext db = null;
        public UserProfileController()
        {
            db = new SegamDBContext();
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string pass1, string pass2)
        {
            if (ModelState.IsValid)
            {
                if (pass1 != pass2)
                {
                    ModelState.AddModelError("", "رمز عبور یکسان نیست");
                }
                else if (string.IsNullOrEmpty(pass1) || string.IsNullOrEmpty(pass2))
                {
                    ModelState.AddModelError("", "رمز عبور نمی تواند خالی باشد");
                }
                else
                {
                    int userId = CurrentUser.PersonID;
                    var person = db.Persons.Find(userId);
                    person.Password = pass1;
                    db.SaveChanges();

                    ViewBag.PassChangeSucc = "رمز عبور با موفقیت تغییر کرد";
                }
            }
            return View();
        }
    }
}

SegamApp/Areas/User/Views/UserProfile/Index.cshtml
@{
    ViewBag.Title = "| پروفایل";
    Layout = "~/Areas/User/Views/Shared/_Layout.cshtml";
}

<h2></h2>

@using (Html.BeginForm("Index", "UserProfile", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>تغییر رمز عبور</h4>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("رمز عبور جدید", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("رمز عبور جدید", null, "pass1", new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessage("pass1","", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.Label("تکرار رمز عبور جدید", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("رمز عبور جدید", null, "pass2", new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessage("pass2","", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <span class="alert-success">@ViewBag.PassChangeSucc</span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-primary" />
            </div>
        </div>

    </div>
}