SegamApp/Areas/Daemon/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataLayer;
using SegamApp.Controllers;

namespace SegamApp.Areas.Daemon.Controllers
{
    [Authorize(Roles = "Daemon")]
    public class GroupsController : BaseController
    {
        private SegamDBContext db = new SegamDBContext();

        // GET: Daemon/Groups
        public ActionResult Index()
        {
            return View(db.Groups.ToList());
        }

        // GET: Daemon/Groups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // GET: Daemon/Groups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Daemon/Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GroupID,GroupName")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(group);
        }

        // GET: Daemon/Groups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Daemon/Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GroupID,GroupName")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }

        // GET: Daemon/Groups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Daemon/Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Group group = db.Groups.Find(id);
            //db.Groups.Remove(group);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SegamApp/Areas/Daemon/Controllers/PeopleController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using DataLayer;
using SegamApp.Controllers;

namespace SegamApp.Areas.Daemon.Controllers
{
    [Authorize(Roles = "Daemon")]
    public class PeopleController : BaseController
    {
        private SegamDBContext db = new SegamDBContext();
        public int ownerID = 0;
        // GET: Daemon/People
        public ActionResult Index()
        {

            ownerID = CurrentUser.PersonID;
            var persons = db.Persons.Where(p => p.CreatorId == ownerID && p.IsDeleted == false);

            return View(persons.ToList());
        }

        // GET: Daemon/People/Create
        public ActionResult Create()
        {
            ViewBag.RoleID = new SelectList(db.Roles, "RoleID", "RoleName");
            return View();
        }

        // POST: Daemon/People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PersonName,PersonEmail,Password,IsDeleted,RoleID")] Person person)
        {
            Person p = db.Persons.Where(pt => pt.PersonEmail == person.PersonEmail && pt.IsDeleted == false).FirstOrDefault();
            if (p != null)
                ModelState.AddModelError("personEmail", "نام کاربری انتخاب شده تکراری می باشد");

            if (ModelState.IsValid)
            {
                ownerID = CurrentUser.PersonID;
                person.CreatorId = ownerID;
                db.Persons.Add(person);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RoleID = new SelectList(db.Roles, "RoleID", "RoleName", person.RoleID);
            return View(person);
        }

        // GET: Daemon/People/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            ViewBag.RoleID = new SelectList(db.Roles, "RoleID", "RoleName", person.RoleID);
            return View(person);
        }

        // POST: Daemon/People/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PersonID,PersonName,PersonEmail,Password,IsDeleted,RoleID,CreatorId")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RoleID = new SelectList(db.Roles, "RoleID", "RoleName", person.RoleID);
            return View(person);
        }

        // GET: Daemon/People/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: Daemon/People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.Persons.Find(id);
            person.IsDeleted = true;
            //db.Persons.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SegamApp/Areas/User/Controllers/HelperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLayer;
using SegamApp.Controllers;
namespace SegamApp.Areas.User.Controllers
{
    [Authorize(Roles = "User")]
    public class HelperController : BaseController
    {
        public string GetNameByUserName(string username)
        {
            var user = "";
            using (SegamDBContext context = new SegamDBContext())
            {
                user = (from u in context.Persons
                        where u.PersonEmail == username
                        select u).FirstOrDefault().PersonName;
            
                return user;
            }
        }
    }
}

SegamApp/Areas/Daemon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>داشبرد مدیر کل سایت @ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-rtl.css" rel="stylesheet" />
    <link href="~/fonts/awsomefonts/all.min.css" rel="stylesheet" />
    <link href="~/fonts/awsomefonts/brands.min.css" rel="stylesheet" />
    <link href="~/fonts/awsomefonts/solid.min.css" rel="stylesheet" />
    <link href="~/fonts/font-injector.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 bg-dark">
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                    <a class="navbar-brand" href="#">داشبورد مدیریتی سامانه گفتار ایرانیان به متن (سگام)</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @Html.Action("GetNameByUserName", "Helper", new { Area = "Daemon", username = User.Identity.Name })
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                                    <a class="dropdown-item" href="#"><span class="fa fa-user-circle"></span> تنظیمات کاربری </a>

                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="/Login/SignOut"><span class="fa fa-sign-out-alt"></span> خروج </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                <div class="card">
                    <div class="card-header bg-primary">
                        <img src="~/Areas/Daemon/images/profile.jpg" style="width:150px; height:150px" />
                        <div class="card-body">
                        </div>
                    </div>
                    <a href="@Url.Action("Index", "Home", new { Area = "Daemon" } )" class="list-group-item list-group-item-action">
                        <span class="fa fa-home"></span>
                        <span>آمار کاربران</span>
                    </a>
                    <a href="@Url.Action("Index", "People", new { Area = "Daemon" } )" class="list-group-item list-group-item-action">
                        <span class="fa fa-user-edit"></span>
                        <span>مدیریت کاربران</span>
                    </a>
                    <a href="@Url.Action("Index", "Groups", new { Area = "Daemon" } )" class="list-group-item list-group-item-action">
                        <span class="fa fa-object-group"></span>
                        <span>مدیریت گروه ها</span>
                    </a>
                    <a href="#" class="list-group-item list-group-item-action disabled">
                        <span class="fa fa-business-time"></span>
                        <span>مدیریت زمان بند</span>
                    </a>
                </div>
            </div>
            <div class="col-md-10">
                <br />
                <br />
                <div class="form-group">
                    @RenderBody()
                </div>
            </div>
        </div>

    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
</body>
</html>